channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.6
  - pandas
  - pytest
  - scikit-bio
  - prodigal
  - scipy<=1.8.1
  - mmseqs2!=10.6d92c
  - hmmer!=3.3.1
  - trnascan-se >=2
  - sqlalchemy
  - barrnap
  - altair >=4
  - openpyxl
  - ruby
  - parallel
  - click
  - pip
  - pip:
    - camper_dramkit

